#!/usr/bin/env bash
# publish-stats.d/update-svc-usage-graph
# 
# Created: 2009-03-07
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2009, Geoul Project. (http://geoul.sparcs.org)
set -e
. "$GEOUL.sh"

[ x"$(dirname "$PWD")" = x"/mirror/svcs" ]
svc=$(basename "$PWD")

draw-pkg-usage() {
    local pkg= name= color=
    eval `load-package pkg name color`
    pkgid=${pkg//./_}
    echo "AREA:${pkgid}_${svc}_usage_size#$color:$name:STACK"
}

{
    for-each-package load-pkg-usage
    for-each-package draw-pkg-usage
    echo "LINE:0#000000::STACK"
    draw-timestamp
} |
render-usage usage.png \
    --title "Network usage of $svc" \
    --width 600 --height 400 \
    "$@"
