#!/usr/bin/env bash
# publish-status -- Publish package status in XML
# 
# Created: 2009-09-15
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006-2009, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
set -e
. "$GEOUL.sh"

# update status.xml
cd /tmp
tmp=`mktemp .geoul.status.xml.XXXXXX`
trap "rm -f $tmp" ERR HUP INT TERM

{
    # TODO self url
    echo '<packages href="" timestamp="'`isodate`'">'
    for-each-package pkg.xml
    echo "</packages>"
} >$tmp
chmod a+r $tmp

mv -f $tmp geoul.status.xml
ln -sf /tmp/geoul.status.xml /mirror/run/status.xml

# vim:ft=sh
