#!/usr/bin/env bash
# run-cvsup -- CVSup wrapper for amd64
# 
# Created: 2006-01-26
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006, Geoul Project. (http://ftp.kaist.ac.kr/geoul)

root=/cvsup
tmp=`mktemp -d "$root/tmp/cvsup.XXXXXX"`
trap "rm -rf $tmp" EXIT

args=()
while arg=$1; shift; do
    # copy to new root and replace if argument is a path to file
    if [ -f "$arg" ]; then
        cp -pf "$arg" "$tmp/"
        arg="${tmp#$root}/`basename "$arg"`"
    elif [ -d "$arg" ]; then
        arg=`readlink -f "$arg"`
        arg=${arg#$root}
    fi
    # accumulate arguments
    args=("${args[@]}" "$arg")
done

"$(dirname "$(readlink -f "$0")")/prepare4amd64" $root

sudo chroot $root sudo -u ${USER:-`whoami`} -H -- \
cvsup "${args[@]}"
