#!/usr/bin/env bash
# geoul-sync -- A wrapper to use geoul sync as an interpreter in synchronization scripts
# 
# Created: 2009-10-13
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006-2009, Geoul Project. (http://project.sparcs.org/geoul)
exec geoul run-sync "$@"
