#!/usr/bin/env bash
. /mirror/lib/sync.sh

set -e
#HOSTNAME=`hostname -f`
HOSTNAME=ftp.kr.debian.org

get $source \
    --exclude=Archive-Update-in-Progress-$HOSTNAME \
    --exclude=data/project/trace/$HOSTNAME
date -u >data/project/trace/$HOSTNAME
