#!/usr/bin/env bash
# synchronized -- Run one process for the command at a time
# 
# Created: 2008-03-05
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2008, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
set -e

# become a process group leader
[ x"`ps -o pgid= -p $$`" == x"$$" ] || exec setsid "$0" "$@"

Lock=$1; shift

# use lockproc to proctect our synchronized command
if lockproc "$Lock" grab; then
    # run the given command
    "$@"
    # release the lock
    lockproc "$Lock" release
else
    exit $?
fi
