#!/usr/bin/env bash
# synchronized -- Run one process for the command at a time
# 
# Created: 2008-03-05
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2008, Geoul Project. (http://ftp.kaist.ac.kr/geoul)

lock=$1; shift

# TODO use lockproc
if lockfile -r3 "$lock" 2>/dev/null; then
    "$@"
    rm -f "$lock"
fi
