#!/usr/bin/env bash
# generate HTML list items of links to data paths of packages
# Usage: list-data-links ROOTPATH
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-01-01
set -eu

Root=$1; shift

. /mirror/lib/geoul.sh

generate-link() {
    local data=`readlink -f data`
    local id=${pkg%/}
    case $data in
        "$Root"/*)
            local relpath=${data#$Root/}
            echo "$id $relpath|$relpath|`cat name`"
            ;;
        *)
            # web mirrors
            if [ -e lighttpd.conf ]; then
                local url="http://`grep server.name lighttpd.conf | head -n 1 | sed 's/.*= *"\|" *$//g'`"
                local name=`cat name`
                echo "${pkg%/} $name|$url|$name"
            fi
            ;;
    esac
}

foreachpkg generate-link |
sort --ignore-case --key=2 |
sed -e 's:\([^ ]*\) \([^|]*\)|\([^|]*\)|\(.*\):<li><a id="\1" title="\4" href="\3/">\2</a></li>:'

# This used to be something like:
#   find * -maxdepth 0 -type d |
#   sort -f |
#   sed -e 's:.*:<li><a href="&/">&</a></li>:'
