#!/usr/bin/env bash
. /mirror/lib/sync.sh
get $source \
    --exclude=bind4/src/DEPRECATED/4.9.5/contrib/old \
    --exclude=RCS --exclude=MIRRORS,v \
    --exclude=pubs/tn/isc-tn-2008-1.tn \
    --exclude='.*\.sigs\.shar' \
    --exclude=bind9/9.7.3-P1/doc \
    --exclude=bind9/9.8.0-P2/doc \
    #
