#!/usr/bin/env bash
. /mirror/lib/sync.sh
get $source <<SUP
cvs-all      release=cvs     prefix=prefixes/FreeBSD.cvs
gnats        release=current prefix=prefixes/FreeBSD-gnats.current
www          release=current prefix=prefixes/FreeBSD-www.current
mail-archive release=current prefix=prefixes/FreeBSD-mail.current
distrib      release=self    prefix=prefixes/distrib.self
SUP
