#!/usr/bin/env bash
# geoul -- A mirror management solution
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006-2009, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
set -e

GEOULSELF=`readlink -f "$0"`
GEOULBASE=`dirname "$GEOULSELF"`
export GEOULSELF GEOULBASE

export PATH="$GEOULBASE:$PATH"
export LC_ALL=C
export LANG=C
export LANGUAGE=C

[ -d "$GEOULDIR" ] || GEOULDIR=$PWD
export GEOULDIR

if Cmd=$1; shift; [ -n "$Cmd" -a -x "$GEOULBASE/$Cmd" ]; then
    # switch running user if defined
    eval `load-config owner`
    if [ -z "$owner" -o x"`whoami`" = x"$owner" ]; then
        exec "$Cmd" "$@"
    else
        exec sudo -H -u "$owner" "$Cmd" "$@"
    fi
else
    [ -z "$Cmd" ] || echo "$Cmd: unknown command" >&2
    echo "Try \`geoul help' for usage."
    exit 1
fi
