#!/usr/bin/env bash
. /mirror/lib/sync.sh
get $source <<SUP
OpenBSD-all      release=cvs  prefix=prefixes/OpenBSD.cvs

# NOTE: -distrib collection is available from cvsup.jp.OpenBSD.org only
OpenBSD-distrib  release=self prefix=prefixes/OpenBSD-distrib.self
SUP
