#!/usr/bin/env bash
# watch-syncs -- Watch running syncs and stop overly inactive ones
# 
# Created: 2007-07-19
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006-2007, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
. "$GEOUL.sh"

# TODO move this to load-config
StopSyncsInactiveFor=${SyncStopInactiveFor:-$((3600*48))}

sync_inactive_for() {
    local activity=`head -1 log; stat -L -c "%Y %s" log`
    if [ -f log.monitor ] && [ "`cat log.monitor`" = "$activity" ]; then
        echo $((`now` - `mtime log.monitor`))
    else
        echo "$activity" >log.monitor
        echo 0
    fi
}

watch() {
    local syncInProgress=
    eval `load-package syncInProgress`
    if $syncInProgress; then
        [ `sync_inactive_for` -lt $StopSyncsInactiveFor ] ||
        ./sync stop "due to no activity"
    fi
}

# FIXME for-each-package does not work for functions
for-each-package watch
