#!/bin/sh
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/c/cvsup/cvsup_16.1e-3_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/c/cvsup/cvsupd_16.1e-3_i386.deb   
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/d/db3/libdb3_3.2.9-16_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/d/debianutils/debianutils_1.16.2woody1_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/f/freetype/libfreetype6_2.0.9-1_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/libc/libcap/libcap1_1.10-12_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/p/pam/libpam-modules_0.72-35_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/p/pam/libpam-runtime_0.72-35_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/p/pam/libpam0g_0.72-35_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/p/pm3/libpm3-extra_1.1.15-1_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/p/pm3/libpm3_1.1.15-1_i386.deb
sudo wget -c http://ftp.kr.debian.org/debian/pool/main/z/zlib/zlib1g_1.1.4-1.0woody0_i386.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/g/glibc/libc6_2.2.5-11.8_i386.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/g/glibc/libc6_2.2.5-11.8_i386.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/s/sudo/sudo_1.6.6-1.6_i386.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/x/xfree86/libxaw7_4.1.0-16woody7_i386.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/x/xfree86/xfree86-common_4.1.0-16woody7_all.deb
sudo wget -c http://security.debian.org/debian-security/pool/updates/main/x/xfree86/xlibs_4.1.0-16woody7_i386.deb
