#!/usr/bin/env bash
# geoul-ftpsync -- a glue layer for using the Debian ftpsync script from Geoul
# 
# This script must be invoked from a Geoul package dir which must contain an
# ftpsync.conf.  A copy of archvsync must exist on the same directory to this
# script.
#
# Created: 2010-09-08
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2010, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
set -eu

Source=$1; shift

Self=`readlink -f "${BASH_SOURCE[0]}"`
Base=`dirname "$Self"`
export BASEDIR="$Base"/archvsync

# prepare environment
hostpath=${Source#rsync://}
export RSYNC_HOST=${hostpath%%/*}
export RSYNC_PATH=${hostpath#$RSYNC_HOST/}
export TO=$PWD/data
name=`basename "$PWD"`
suffix=${name#debian}
ARCHIVE=${suffix#-}
export ARCHIVE

# install configuration
conf="ftpsync$suffix.conf"
confpath="$BASEDIR/etc/$conf"
[ -e "$confpath" ] || ln -sfn "$PWD"/ftpsync.conf "$confpath"

# final check before take-off
[ -e ftpsync.conf ]
[ -d "$TO" ]

# prepare hooks
export triggered timepast failures
. "$Base"/geoul-ftpsync.prepare
export HOOK6="$Base/geoul-ftpsync.finish $PWD $log $suffix"

# let Debian's ftpsync handle the actual sync
"$BASEDIR"/bin/ftpsync
