#!/usr/bin/env bash
# Push server implementation for secondary push-triggered Debian mirrors
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-02-14
# See: http://www.debian.org/mirror/push_server#sshtrigger

. /mirror/lib/geoul.sh

running_as_mirror_admin "$@"

options=()
if [ $# -eq 0 ]; then
    set -- `sed 's/#.*$//' <downstreams`
    options=("${options[@]}" -o "BatchMode yes")
else
    options=("${options[@]}" -v)
fi
unset SSH_AUTH_SOCK

set -e -x
for downstream in "$@"
do ssh "${options[@]}" -i ~/.ssh/id_rsa $downstream true
done
