#!/usr/bin/env bash
# expire-sync-logs -- Sync log cleaning script
# 
# Created: 2006-10-30
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
. "$GEOUL.sh"

days=60

cd /mirror/log/sync

# remove old logs
find . -mtime +$days -type f -exec rm -f {} \;

# remove empty dirs
find . -type d -exec rmdir -p {} \; 2>/dev/null
