#!/usr/bin/env bash
. /mirror/lib/sync.sh

set -e

#HOSTNAME=`hostname -f`
HOSTNAME=ftp.kr.debian.org
umask 002

# load private info
set +x
. debian-ftpsync.conf
export RSYNC_PASSWORD
source=${source/:\/\//:\/\/$RSYNC_USER@}
set -x

# first, get new debs (not touching removed ones or indices)
rsync --recursive --times --links --hard-links \
      --exclude "Packages*" --exclude "Sources*" \
      --exclude "Release*" --exclude "ls-lR*" \
      --verbose --stats \
      $source data/

# then, synchronize indices and everything else
rsync --recursive --times --links --hard-links --max-delete=40000 \
      --delete --delete-after --delay-updates\
      --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
      --exclude "project/trace/${HOSTNAME}" \
      --verbose --stats \
      $source data/

# now, place a timestamp
date -u >data/project/trace/${HOSTNAME}

#./push
