#!/usr/bin/env bash
. /mirror/lib/sync.sh

set -e

HOSTNAME=`hostname -f`
#HOSTNAME=ftp.kr.debian.org
umask 002

# load private info
set +x
. debian-ftpsync.conf
export RSYNC_PASSWORD
set -x

source=${source/:\/\//:\/\/$RSYNC_USER@}

#why these two rsync steps are required? i don't know why - blmarket

rsync --recursive --times --links --hard-links \
      --exclude "Packages*" --exclude "Sources*" \
      --exclude "Release*" --exclude "ls-lR*" \
      --verbose --stats \
      $source data/

rsync --recursive --times --links --hard-links --max-delete=40000 \
      --delete --delete-after --delay-updates\
      --exclude "Archive-Update-in-Progress-${HOSTNAME}" \
      --exclude "project/trace/${HOSTNAME}" \
      --verbose --stats \
      $source data/

date -u >data/project/trace/${HOSTNAME}

#./push
