#!/usr/bin/env bash
# run-cvsup -- run CVSup with given supfile
# 
# Created: 2006-01-26
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006, Geoul Project. (http://ftp.kaist.ac.kr/geoul)
set -e

sup=$PWD/$1

# making sure that cvsup runs without -s flag once a day
sflag=-s
day=`date +%d`
if ! [ -e day ] || [ `cat day` != $day ]; then
    sflag=
fi

sudo chroot /cvsup sudo -H -u mirror \
cvsup $sflag -g -L 2 -r 0 "$sup" && echo $day >day
