#!/usr/bin/env bash
# run-cvsup -- CVSup wrapper for amd64
# 
# Created: 2006-01-26
# 
# Written by Jaeho Shin <netj@sparcs.org>.
# (C) 2006, Geoul Project. (http://ftp.kaist.ac.kr/geoul)

exec sudo chroot /cvsup sudo -H -u $USER \
cvsup "$@"
