#!/usr/bin/env bash
. /mirror/lib/sync.sh

# load private info
set +x
. gentoo-rsync.conf
export RSYNC_PASSWORD
set -x

get $source --exclude=/releases/lost+found --exclude=/releases/.test/THIS-FILE-SHOULD-NOT-BE-PUBLIC.txt
